name: Publish image to Dockerhub # workflow名称

on: # 配置触发
  push:
    tags: # tag更新时触发workflow
      - 'v*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub # job名字
    runs-on: ubuntu-latest # job运行的基础环境
    steps:  # 一个job由一个或多个stp组成
      - name: Check out the repo
        uses: actions/checkout@v3   # 官方的action，获取代码

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: newreport/api_upload

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
